version: "2.1"
services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    environment:
      MYSQL_DATABASE: wallet
      MYSQL_USER: cdc
      MYSQL_PASSWORD: cdcpwd
      MYSQL_ROOT_PASSWORD: rootpwd
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "mysql --host=localhost --user=$$MYSQL_USER --password=$$MYSQL_PASSWORD --silent --execute \"SELECT 1;\"  || exit 0"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - wallet_network

  app:
    build: .
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_NAME=wallet
      - DB_PORT=3306
      - DB_USER=cdc
      - DB_PASSWORD=cdcpwd
      - API_PORT=8080
    ports:
      - 8080:8080
    networks:
      - wallet_network

networks:
  wallet_network:
