// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bank "github.com/n3k0fi5t/wallet/app/models/bank"
import context "context"
import mock "github.com/stretchr/testify/mock"

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// Deposit provides a mock function with given fields: ctx, accountID, amount
func (_m *Service) Deposit(ctx context.Context, accountID string, amount int64) (string, error) {
	ret := _m.Called(ctx, accountID, amount)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = rf(ctx, accountID, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, accountID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAccount provides a mock function with given fields: ctx, accountID
func (_m *Service) GetAccount(ctx context.Context, accountID string) (*bank.Account, error) {
	ret := _m.Called(ctx, accountID)

	var r0 *bank.Account
	if rf, ok := ret.Get(0).(func(context.Context, string) *bank.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Transfer provides a mock function with given fields: ctx, from, to, amount
func (_m *Service) Transfer(ctx context.Context, from string, to string, amount int64) (string, error) {
	ret := _m.Called(ctx, from, to, amount)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) string); ok {
		r0 = rf(ctx, from, to, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, from, to, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Withdraw provides a mock function with given fields: ctx, accountID, amount
func (_m *Service) Withdraw(ctx context.Context, accountID string, amount int64) (string, error) {
	ret := _m.Called(ctx, accountID, amount)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) string); ok {
		r0 = rf(ctx, accountID, amount)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = rf(ctx, accountID, amount)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
