// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import bank "github.com/n3k0fi5t/wallet/app/models/bank"
import context "context"
import mock "github.com/stretchr/testify/mock"

// Bank is an autogenerated mock type for the Bank type
type Bank struct {
	mock.Mock
}

// GetAccount provides a mock function with given fields: ctx, accountID
func (_m *Bank) GetAccount(ctx context.Context, accountID string) (*bank.Account, error) {
	ret := _m.Called(ctx, accountID)

	var r0 *bank.Account
	if rf, ok := ret.Get(0).(func(context.Context, string) *bank.Account); ok {
		r0 = rf(ctx, accountID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*bank.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, accountID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Trade provides a mock function with given fields: ctx, dealing
func (_m *Bank) Trade(ctx context.Context, dealing *bank.Dealing) (string, error) {
	ret := _m.Called(ctx, dealing)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, *bank.Dealing) string); ok {
		r0 = rf(ctx, dealing)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *bank.Dealing) error); ok {
		r1 = rf(ctx, dealing)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
